### PR TITLE
locations in the dashboard filtered by ownerId. Get locations action …

### PR DESCRIPTION
**Pull request by salihovdr**
…configured to take in variety of filters

### CODE REVIEW

**Comment by MitchGianoni** [comment]
tested this, it looks like all that is happening right now is it removes locations posted by other users from my dashboard. work in progress still?

**Comment by salihovdr** [comment]
> tested this, it looks like all that is happening right now is it removes locations posted by other users from my dashboard. work in progress still?

Yes, because that's the filter I set. You can change the query as necessary.

**Comment by adesi006** [comment]
Got same result. Will go over after morning scrum

**Comment by MitchGianoni** [comment]
Is this something we want to merge in eventually?

**Pull request merged**
