### PR TITLE
added image update feature

### PR DESCRIPTION
**Pull request by salihovdr**

### CODE REVIEW

**Comment by MitchGianoni** [comment]
tested this, doesn't look like image is changing properly. When I select a new image from my local computer, nothing happens and then upon refresh there is no image on the page. When hitting back to dashboard after that it logs me out of the application entirely. That might be a separate bug entirely but I think it is worth noting.

**Comment by salihovdr** [comment]
> tested this, doesn't look like image is changing properly. When I select a new image from my local computer, nothing happens and then upon refresh there is no image on the page. When hitting back to dashboard after that it logs me out of the application entirely. That might be a separate bug entirely but I think it is worth noting.

Do you have the most recent server? What errors are you getting?

**Comment by salihovdr** [comment]
> > tested this, doesn't look like image is changing properly. When I select a new image from my local computer, nothing happens and then upon refresh there is no image on the page. When hitting back to dashboard after that it logs me out of the application entirely. That might be a separate bug entirely but I think it is worth noting.
> 
> Do you have the most recent server? What errors are you getting?

My bad! Turns out I didn't push the backend code with the image edit endpoint. It's there now. Make a new pull before testing again

**Comment by adesi006** [comment]
Getting a 500 error when I try to add an image. I've pulled down the most recent master branch. is there anything else I might have needed to know?

**Pull request merged**
